output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "jenkins_server_public_address" {
    value = aws_instance.jenkins_server.*.public_ip
}
output "jenkins_ubuntu-nodes_public_addresses" {
    value = aws_instance.ubuntu-nodes.*.public_ip
}

output "consul-server_private_addresses" {
    value = aws_instance.consul_server.*.private_ip
}